task.template.allowMultipleTasksFromTemplate: false
spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:\\Users\\Arielka\\Desktop\\projekt_przyszly_programista\\java\\0_java_web\\Spring-framework\\todo-app\\todo-app\\todo-db'
  jpa.hibernate:
    ddl-auto: create-drop
  main:
    banner-mode: off




