management.endpoints.web.base-path: /status
management:
  metrics:
    enable:
      http: false
spring.profiles.active: local
spring.main.banner-mode: off
server.error.include-message: always
task.template.allowMultipleTasksFromTemplate: false




